%This function reads a workspace of pictures taken for a calibration matrix
%and outputs the matrix.

function [CalibrationMatrix] = CalibrationMatrix(Cal_BcCP1_BcCP2,...
    Cal_BcCP1_BlCP2, Cal_BcCP1_GlCP2, Cal_BcCP1_OlCP2, Cal_BlCP1_BcCP2,...
    Cal_BlCP1_BlCP2, Cal_BlCP1_GlCP2, Cal_BlCP1_OlCP2, Cal_GlCP1_BcCP2, ...
    Cal_GlCP1_BlCP2, Cal_GlCP1_GlCP2, Cal_GlCP1_OlCP2, Cal_OlCP1_BcCP2, ...
    Cal_OlCP1_BlCP2, Cal_OlCP1_GlCP2, Cal_OlCP1_OlCP2, LaserPolarization)

